a new masterfile
Orbis-Amadeus-Oxford/Amadeus-Datawork pull request #14
Opened 2018-11-22 11:35 UTC by yangjh2612

I change our master file quite significantly. I wanted to use a more rigorous definition of our variables. 

When we use EBTA (Earnings before Interest, Tax, and D&A) we need to add D&A back to capital stock since assets are recorded in net value (after D&A) on a balance sheet. Also, both EBIT and EBTA record only operating earnings excluding financial earnings, and therefore it makes more sense to use the fixed asset (= total asset - current asset) in calculating capital productivity. 

In calculating the rate of profit, we now have five different measures 
1) Cash Flow ( = Operating Earnings + Financial Earnings + Tax + Depreciation)/(TOAS+ Depreciation)
2) Total gross Profit  ( = Operating Earnings + Financial Earnings + Tax) /TOAS
3) Total net Profit  ( = Operating Earnings + Financial Earnings ) /TOAS
4) EBTA ( = Operating Earnings + Tax + Depreciation)/ (FIAS + Depreciation)
5) EBIT ( = Operating Earnings + Tax)/ FIAS

In this new script, there is no deflator, so please feel free to add it. Also, I removed the NAICS code filter since we are not going to use it. Finally, if you want to add more variables, e.g. R&D related variables, please feel free to do it. If you want to understand how Orbis variables are constructed, see pp 412 - 505 of the file I'll send you separately via email.

Any comments and suggestions are welcome!

2018-11-22 11:57 UTC, mumblecrust reviewed
Just to check so I understand:
EBITA is the same as EBITDA?
FIAS includes DEPR, hence you add it back in when you want profits after depreciation?

2018-11-22 13:02 UTC, mumblecrust approved these changes

2018-11-22 18:29 UTC, x0range requested changes
I would strongly suggest to never push non-working code. 

  1 `lapply` in line `163` hands over three arguments, the function `fun_data_clean` in line `15` accepts only one. Reason for this is that the deflator was temporarily removed. Please change either function call or function definition, otherwise this will throw an error.
  2. Typo in variable name in line `79` (should be `WS_AD`, not `WD_AD`). Please correct.
  3. Trailing dplyr pipe (`%>%`) in line `85`. This throws an error as the following return function is not recognized as a separate command. Please remove.
  4. Minor comment: I like the commenting in lines `34` - `58`. However, I think, we could be even a bit more explicit and also state the meaning of the Orbis variable names, so that the code is readable even for those unfamiliar with the BvD's variable names (which are non-intuitive and good examples for how not to choose variable names). No immediate change required, but we should consider extending the commenting in the future.
  5. Minor comment: Some old comments are confusing: The double `# Functions` section comment in lines `11`-`12`, the old sequence number 8 in line `205` (should be 6). This is minor and not very important, but we should not forget to take care of this eventually.

2018-11-22 22:59 UTC, yangjh2612 commented
I would strongly suggest to never push non-working code.

-> makes a lot of sense. Getting more serious about gitbut little by little
thanks to you.


1 lapply in line 163 hands over three arguments, the function fun_data_clean in
line 15 accepts only one. Reason for this is that the deflator was
temporarily removed. Please change either function call or function
definition, otherwise this will throw an error.

-> yep will correct it.


2. Typo in variable name in line 79 (should be WS_AD, not WD_AD). Please
correct.

-> Well spotted. will correct it.


3. Trailing dplyr pipe (%>%) in line 85. This throws an error as the
following return function is not recognized as a separate command. Please
remove.

-> yep will correct it.


4. Minor comment: I like the commenting in lines 34 - 58. However, I think,
we could be even a bit more explicit and also state the meaning of the
Orbis variable names, so that the code is readable even for those
unfamiliar with the BvD's variable names (which are non-intuitive and good
examples for how not to choose variable names). No immediate change
required, but we should consider extending the commenting in the future.

-> yep makes sense. Will put more efforts to make the script readable.


5. Minor comment: Some old comments are confusing: The double #
Functions section
comment in lines 11-12, the old sequence number 8 in line 205 (should be
6). This is minor and not very important, but we should not forget to take
care of this eventually.

-> Will take care of this as well.


Thanks a lot for your comments! Very useful as always.

On Thu, Nov 22, 2018 at 6:29 PM x0range <notifications@github.com> wrote:

> *@x0range* requested changes on this pull request.
>
> I would strongly suggest to never push non-working code.
>
> 1 lapply in line 163 hands over three arguments, the function
> fun_data_clean in line 15 accepts only one. Reason for this is that the
> deflator was temporarily removed. Please change either function call or
> function definition, otherwise this will throw an error.
> 2. Typo in variable name in line 79 (should be WS_AD, not WD_AD). Please
> correct.
> 3. Trailing dplyr pipe (%>%) in line 85. This throws an error as the
> following return function is not recognized as a separate command. Please
> remove.
> 4. Minor comment: I like the commenting in lines 34 - 58. However, I
> think, we could be even a bit more explicit and also state the meaning of
> the Orbis variable names, so that the code is readable even for those
> unfamiliar with the BvD's variable names (which are non-intuitive and good
> examples for how not to choose variable names). No immediate change
> required, but we should consider extending the commenting in the future.
> 5. Minor comment: Some old comments are confusing: The double # Functions
> section comment in lines 11-12, the old sequence number 8 in line 205
> (should be 6). This is minor and not very important, but we should not
> forget to take care of this eventually.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Orbis-Amadeus-Oxford/Amadeus-Datawork/pull/14#pullrequestreview-177753464>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ap_I8rARYKAqfi91sWnub-niN1A7UZ8Sks5uxuzwgaJpZM4YvLOU>
> .
>

2018-11-24 12:31 UTC, yangjh2612 commented
I corrected some errors in the master file as Torsten pointed out. It runs well now. I also change the integer64 data type to numerics. It doesn't really change much except for a few values. I just did it because I don't like the error messages like NA produced by integer64 overflows...

2018-11-24 19:47 UTC, x0range approved these changes

2018-11-24 19:47 UTC, merged