Update masterfile
Orbis-Amadeus-Oxford/Amadeus-Datawork pull request #27
Opened 2019-03-13 02:00 UTC by x0range

As discussed.

Please especially check:
  * That there are no errors. (As you know, I can't test this.)
  * How the computations of log returns and diffs for Zeta should be done; lines `176ff` and `201ff`
  * Whether we indeed want the deflated variables in the `All_list_Cleaned.Rda`, lines `373ff`
  * Whether it is acceptable to write `All_list_Cleaned.Rda` from this file, line `448`

Regarding the last point: Up until now, that file has been produced by another file and I honestly do not know which one. The data file is the master dataset. Since the variables do not seem to have undergone any additional modifications, however, I think that data file should be written by this masterfile script. That the masterfile also writes the `panels*.Rda` files is fine.

Also note that I included the firm age in the master dataset. We may want to use that at some point.

2019-03-14 02:23 UTC, x0range commented
Updated as per discussion results from today. Option to deflate LP but not CP for computation of TFP related variables (`lpdef_*`) cannot consistently be done with negative support and has therefore been removed.

2019-03-14 13:34 UTC, yangjh2612 requested changes
1. In the previous script, AD means After Depreciation not After Deflation. 

For example, CP_AD is capital productivity after depreciation (Wages + Profits + Taxes + Interest)/Fixed Asset (or EBIT/FiAS) while CP is capital productivity before depreciation (Wages + Profits + Taxes + Interest + Depreciation)/(Fixed Asset + Depreciation) or (EBTA/FIAS + DEPR).

We used the measures before depreciation in our main text, which I believe is a better way to impute the value added (profits vs. cash flow) and is what OECD people do as well. 

JH

2019-03-14 14:55 UTC, x0range commented
@yangjh2612 I do not use `_AD` to denote "after deflation". In line with the previous convention, I continued to use prefix `def_` for this. 
In case you meant that I use the wrong value added to compute `TFP_AD` and `def_TFP_AD`, you are right. I corrected this.

2019-03-14 14:57 UTC, yangjh2612 commented
Great. That's what I meant.



On Thu, Mar 14, 2019 at 2:56 PM x0range <notifications@github.com> wrote:

> @yangjh2612 <https://github.com/yangjh2612> I do not use _AD to denote
> "after deflation". In line with the previous convention, I continued to use
> prefix def_ for this.
> In case you meant that I use the wrong value added to compute TFP_AD and
> def_TFP_AD, you are right. I corrected this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Orbis-Amadeus-Oxford/Amadeus-Datawork/pull/27#issuecomment-472901432>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ap_I8ldBV0_B3js8U11N1DjXbDxcRWHDks5vWmLogaJpZM4bsO4y>
> .
>

2019-03-15 16:50 UTC, mumblecrust approved these changes
Is ZOMBIE_AD necessary? Surely a zombie is zombie regardless of deflation (since you are just multiplying the price index)

2019-03-15 17:48 UTC, x0range commented
@mumblecrust 

> Is ZOMBIE_AD necessary? Surely a zombie is zombie regardless of deflation (since you are just multiplying the price index)

No, it is unfortunately not. Value added is `VA` and `VA_AD` respectively, either or both of which can be negative. The difference is that they are computed from `EBIT` and `EBTA` respectively, earnings before and after depreciation (and amortization??).

2019-03-18 08:48 UTC, mumblecrust commented
Ah ok, that makes sense. Thanks!

2019-03-18 18:22 UTC, yangjh2612 approved these changes
Sorry for the delay!

2019-03-18 18:26 UTC, merged